### ISSUE TITLE
Caprover not running after droplet install

### ISSUE THREAD

**Issue by kevin8181** [caprover/digital-ocean-marketplace#2]
I just created a droplet using the image and it did not start caprover after install. ip:3000 in browser could not connect. sshed in and there were no docker containers running

**Comment by kevin8181** [comment]
@githubsaturn

**Comment by githubsaturn** [comment]
@kevin8181 - there was an issue with DigitalOcean one click app unfortunately it's a long weekend in the US and it'll be a while before they fix it.

Until then, please just simply run:
```bash
docker run -p 80:80 -p 443:443 -p 3000:3000 -e ACCEPTED_TERMS=true -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
```
